apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authentik.fullname" . }}-config
data:
  POSTGRESQL__HOST: "{{ .Release.Name }}-postgresql"
  POSTGRESQL__NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  POSTGRESQL__USER: "{{ .Values.postgresql.postgresqlUsername }}"
  {{- if .Values.backup }}
  POSTGRESQL__S3_BACKUP__ACCESS_KEY: "{{ .Values.backup.accessKey }}"
  POSTGRESQL__S3_BACKUP__BUCKET: "{{ .Values.backup.bucket }}"
  POSTGRESQL__S3_BACKUP__REGION: "{{ .Values.backup.region }}"
  POSTGRESQL__S3_BACKUP__HOST: "{{ .Values.backup.host }}"
  {{- end}}
  REDIS__HOST: "{{ .Release.Name }}-redis-master"
  ERROR_REPORTING__ENABLED: "{{ .Values.config.errorReporting.enabled }}"
  ERROR_REPORTING__ENVIRONMENT: "{{ .Values.config.errorReporting.environment }}"
  ERROR_REPORTING__SEND_PII: "{{ .Values.config.errorReporting.sendPii }}"
  LOG_LEVEL: "{{ .Values.config.logLevel }}"
  OUTPOSTS__DOCKER_IMAGE_BASE: "{{ .Values.image.name_outposts }}"
  EMAIL__HOST: "{{ .Values.config.email.host }}"
  EMAIL__PORT: "{{ .Values.config.email.port }}"
  EMAIL__USERNAME: "{{ .Values.config.email.username }}"
  EMAIL__USE_TLS: "{{ .Values.config.email.use_tls }}"
  EMAIL__USE_SSL: "{{ .Values.config.email.use_ssl }}"
  EMAIL__TIMEOUT: "{{ .Values.config.email.timeout }}"
  EMAIL__FROM: "{{ .Values.config.email.from }}"
