{{- range list "server" "worker" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "common.names.fullname" $) . }}
  labels:
  {{- include "common.labels" $ | nindent 4 }}
spec:
  {{ if eq . "server" -}}
  replicas: {{ $.Values.replicas }}
  {{- else -}}
  replicas: {{ $.Values.worker.replicas }}
  {{- end }}
  selector:
    matchLabels:
  {{- include "common.labels" $ | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "common.labels" $ | nindent 8 }}
    spec:
      {{- if $.Values.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.fullname" $ }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: true
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ $.Values.image.name }}:{{ $.Values.image.tag }}"
          imagePullPolicy: "{{ $.Values.image.pullPolicy }}"
          args: [{{ quote . }}]
          env:
            {{- range $k, $v := $.Values.env }}
            - name: {{ quote $k }}
              value: {{ quote $v }}
            {{- end }}
            {{- include "authentik.env" (dict "root" $ "values" $.Values.authentik) | indent 12 }}
            {{- range $name, $val := $.Values.envValueFrom }}
            - name: {{ $name }}
              valueFrom:
                {{- toYaml $val | nindent 16 }}
            {{- end }}
            {{- with $.Values.envFrom }}
          envFrom:
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with $.Values.volumeMounts }}
          volumeMounts:
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if eq . "server" }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: https
              containerPort: 9443
              protocol: TCP
              {{- if $.Values.livenessProbe.enabled }}
                {{- with omit $.Values.livenessProbe "enabled" }}
          livenessProbe:
                  {{- toYaml . | nindent 12 }}
                {{- end }}
              {{- end }}
              {{- if $.Values.readinessProbe.enabled }}
                {{- with omit $.Values.readinessProbe "enabled" }}
          readinessProbe:
                  {{- toYaml . | nindent 12 }}
                {{- end }}
              {{- end }}
            {{- end }}
            {{- with index $.Values.resources . }}
          resources:
              {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with $.Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
