apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "authentik.fullname" . }}-uploads
  labels:
    app.kubernetes.io/name: {{ include "authentik.name" . }}
    helm.sh/chart: {{ include "authentik.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.pvc.mode }}
  storageClassName: {{ .Values.pvc.uploadsStorageClass }}
  resources:
    requests:
      storage: {{ .Values.pvc.uploadsSize }}
