replicas: 1

image:
  name: ghcr.io/goauthentik/authentik
  tag: 2021.4.5
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  labels: {}
  hosts:
    - host: authentik.domain.tld
      paths:
        - path: "/"
          pathType: Prefix

authentik:
  log_level: ""
  email:
    host: 10
    port: ""
    username: ""
    use_tls: ""
    use_ssl: ""
    timeout: ""
    from: ""
  outposts:
    docker_image_base: ""
  error_reporting:
    enabled: false
    environment: ""
    send_pii: ""
  postgresql:
    host: ""
    database: ""
    user: ""
    s3_backup:
      access_key: ""
      bucket: ""
      region: ""
      host: ""
  redis:
    host: ""
    password: ""

# see configuration options at https://goauthentik.io/docs/installation/docker-compose-config/
env: {}

envFrom: []

service:
  enabled: true
  type: ClusterIP
  port: 80
  name: http
  protocol: TCP
  labels: {}
  annotations: {}

volumes: []

volumeMounts: []

affinity: {}

resources:
  server: {}
  worker: {}

livenessProbe:
  enabled: true
  httpGet:
    path: /-/health/live/
    port: http
  initialDelaySeconds: 15
  periodSeconds: 30

readinessProbe:
  enabled: true
  httpGet:
    path: /-/health/ready/
    port: http
  initialDelaySeconds: 15
  periodSeconds: 30

serviceAccount:
  create: true

prometheus:
  serviceMonitor:
    create: false
    interval: 10s
    scrapeTimeout: 3s
    secret:
      name: ""
      # username currently _MUST_ be "monitor"
      usernameKey: ""
      passwordKey: ""
  rules:
    create: false

geoip:
  enabled: false
  schedule: "0 */8 * * *"
  accountId: ""
  licenseKey: ""
  editionIds: "GeoLite2-City"

postgresql:
  enabled: false
  # postgresqlUsername: ""
  # postgresqlPassword: ""
  # postgresqlDatabase: ""
  # persistence:
  #   enabled: true
  #   storageClass:
  #   accessModes:
  #     - ReadWriteOnce
redis:
  enabled: false
  auth:
    enabled: false
