replicas: 1

worker:
  replicas: 1

image:
  name: ghcr.io/goauthentik/server
  tag: 2021.5.2
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  labels: {}
  hosts:
    - host: authentik.domain.tld
      paths:
        - path: "/"
          pathType: Prefix

authentik:
  # -- Log level for server and worker
  log_level: info
  # -- Secret key used for cookie singing and unique user IDs,
  # don't change this after the first install
  secret_key: ""
  email:
    host: ""
    port: 587
    username: ""
    use_tls: false
    use_ssl: false
    timeout: 30
    from: ""
  outposts:
    # -- Template used for managed outposts. The following placeholders can be used
    # %(type)s - the type of the outpost
    # %(version)s - version of your authentik install
    # %(build_hash)s - only for beta versions, the build hash of the image
    docker_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
  error_reporting:
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.beryju.org, and is fully opt-in
    enabled: false
    environment: "k8s"
    send_pii: false
  postgresql:
    # -- set the postgresql hostname to talk to
    # if unset and .Values.postgresql.enabled == true, will generate the default
    # @default -- `{{ .Release.Name }}-postgresql`
    host: '{{ .Release.Name }}-postgresql'
    name: ""
    user: ""
    password: ""
    port: 5432
    # -- optional S3 backup, backs the full database up once a day
    s3_backup:
      access_key: ""
      secret_key: ""
      bucket: ""
      region: ""
      host: ""
      location: ""
  redis:
    # -- set the redis hostname to talk to
    # @default -- `{{ .Release.Name }}-redis-master`
    host: '{{ .Release.Name }}-redis-master'
    password: ""

# -- see configuration options at https://goauthentik.io/docs/installation/configuration/
env: {}
# AUTHENTIK_VAR_NAME: VALUE

envFrom: []
#  - configMapRef:
#      name: special-config

envValueFrom: {}
#  AUTHENTIK_VAR_NAME:
#    secretKeyRef:
#      key: password
#      name: my-secret

service:
  enabled: true
  type: ClusterIP
  port: 80
  name: http
  protocol: TCP
  labels: {}
  annotations: {}

volumes: []

volumeMounts: []

affinity: {}

resources:
  server: {}
  worker: {}

# WARNING! When initially deploying, authentik has to do a few DB migrations. This may cause it to die from probe
# failure, but will continue on reboot. You can disable this during deployment if this is not desired
livenessProbe:
  # -- enables or disables the livenessProbe
  enabled: true
  httpGet:
    # -- liveness probe url path
    path: /-/health/live/
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /-/health/ready/
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10

serviceAccount:
  create: true

prometheus:
  serviceMonitor:
    create: false
    interval: 10s
    scrapeTimeout: 3s
    secret:
      name: ""
      # username currently _MUST_ be "monitor"
      usernameKey: ""
      passwordKey: ""
  rules:
    create: false

geoip:
  enabled: false
  schedule: "0 */8 * * *"
  accountId: ""
  licenseKey: ""
  editionIds: "GeoLite2-City"

postgresql:
  enabled: false
  postgresqlUsername: "authentik"
  # postgresqlPassword: ""
  postgresqlDatabase: "authentik"
  # persistence:
  #   enabled: true
  #   storageClass:
  #   accessModes:
  #     - ReadWriteOnce
redis:
  enabled: false
  auth:
    enabled: false
