replicas: 1

image:
  name: ghcr.io/goauthentik/authentik
  tag: 2021.4.5
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  ingressClassName: ""
  annotations: { }
  labels: { }
  hosts:
    - host: authentik.domain.tld
      paths:
        - path: "/"
          pathType: Prefix

# see more configuration options at https://goauthentik.io/docs/installation/docker-compose-config/
env:
  OUTPOSTS__DOCKER_IMAGE_BASE: "ghcr.io/goauthentik/authentik"
  # SECRET_KEY: ""
  # POSTGRESQL__S3_BACKUP__SECRET_KEY: ""
  # EMAIL__PASSWORD: ""
  # POSTGRESQL__HOST: ""
  # POSTGRESQL__NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  # POSTGRESQL__USER: "{{ .Values.postgresql.postgresqlUsername }}"
  # POSTGRESQL__S3_BACKUP__ACCESS_KEY: "{{ .Values.backup.accessKey }}"
  # POSTGRESQL__S3_BACKUP__BUCKET: "{{ .Values.backup.bucket }}"
  # POSTGRESQL__S3_BACKUP__REGION: "{{ .Values.backup.region }}"
  # POSTGRESQL__S3_BACKUP__HOST: "{{ .Values.backup.host }}"
  # REDIS__HOST: "{{ .Release.Name }}-redis-master"
  # ERROR_REPORTING__ENABLED: "{{ .Values.config.errorReporting.enabled }}"
  # ERROR_REPORTING__ENVIRONMENT: "{{ .Values.config.errorReporting.environment }}"
  # ERROR_REPORTING__SEND_PII: "{{ .Values.config.errorReporting.sendPii }}"
  # LOG_LEVEL: "{{ .Values.config.logLevel }}"
  # OUTPOSTS__DOCKER_IMAGE_BASE: "{{ .Values.image.name_outposts }}"
  # EMAIL__HOST: "{{ .Values.config.email.host }}"
  # EMAIL__PORT: "{{ .Values.config.email.port }}"
  # EMAIL__USERNAME: "{{ .Values.config.email.username }}"
  # EMAIL__USE_TLS: "{{ .Values.config.email.use_tls }}"
  # EMAIL__USE_SSL: "{{ .Values.config.email.use_ssl }}"
  # EMAIL__TIMEOUT: "{{ .Values.config.email.timeout }}"
  # EMAIL__FROM: "{{ .Values.config.email.from }}"
envFrom: []

service:
  enabled: true
  type: ClusterIP
  port: 80
  name: http
  protocol: TCP
  labels: { }
  annotations: { }

volumes: []

volumeMounts: []

affinity: { }

resources:
  server: { }
  worker: { }

livenessProbe:
  enabled: true
  httpGet:
    path: /-/health/live/
    port: http
  initialDelaySeconds: 15
  periodSeconds: 30

readinessProbe:
  enabled: true
  httpGet:
    path: /-/health/ready/
    port: http
  initialDelaySeconds: 15
  periodSeconds: 30

serviceAccount:
  create: true

prometheus:
  serviceMonitor:
    create: false
    interval: 10s
    scrapeTimeout: 3s
    secret:
      name: ""
      # username currently _MUST_ be "monitor"
      usernameKey: ""
      passwordKey: ""
  rules:
    create: false

geoip:
  enabled: false
  schedule: "0 */8 * * *"
  accountId: ""
  licenseKey: ""
  editionIds: "GeoLite2-City"

postgresql:
  enabled: false
  # postgresqlUsername: ""
  # postgresqlPassword: ""
  # postgresqlDatabase: ""
  # persistence:
  #   enabled: true
  #   storageClass:
  #   accessModes:
  #     - ReadWriteOnce
redis:
  enabled: false
  auth:
    enabled: false
